name: weather
description: "Weather"
publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: 3.19.1
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  intl: ^0.19.0
  skeletonizer: ^1.1.0

  geolocator: ^11.0.0
  geocoding: ^2.2.0

  shared_preferences: ^2.2.2
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
